apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-6-3-deployment
spec:
  selector:
    matchLabels:
      app: task-6-3
  replicas: 2
  template:
    metadata:
      labels:
        app: task-6-3
    spec:
      containers:
        - name: task-6-3
          image: nanajanashia/argocd-app:1.2
          ports:
            - containerPort: 8080
